---
name: prometheus

instance_groups:
  - name: alertmanager
    azs: ((azs))
    instances: 1
    vm_type: medium
    persistent_disk: ((alertmanager_persistent_disk))
    stemcell: default
    networks:
    - name: ((network))
    jobs:
      - name: alertmanager
        release: prometheus
        properties:
          alertmanager:
            route:
              receiver: default
              group_by:
              - alertname
              group_interval: 15m
              group_wait: 5m
              repeat_interval: 8h
              severity: critical
            receivers:
              - name: default
            test_alert:
              daily: true

  - name: prometheus2
    azs: ((azs))
    instances: 1
    vm_type: medium
    persistent_disk: ((prometheus_persistent_disk))
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: prometheus2
        release: prometheus
        properties:
          prometheus:
            storage:
              tsdb:
                retention: 
                  time: ((prometheus_retention))
            rule_files:
              - /var/vcap/jobs/postgres_alerts/*.alerts.yml
              - /var/vcap/jobs/prometheus_alerts/*.alerts.yml
            scrape_configs:
              - job_name: prometheus
                static_configs:
                - targets:
                  - localhost:9090
      - name: postgres_alerts
        release: prometheus
      - name: prometheus_alerts
        release: prometheus

  - name: database
    azs: ((azs))
    instances: 1
    vm_type: medium
    persistent_disk: ((prometheus_database_persistent_disk))
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: postgres
        release: postgres
        properties:
          databases:
            port: 5432
            databases:
              - name: grafana
                citext: true
            roles:
              - name: grafana
                password: ((postgres_grafana_password))
      - name: postgres_exporter
        release: prometheus
        properties:
          postgres_exporter:
            datasource_name: postgresql://grafana:((postgres_grafana_password))@127.0.0.1:5432/?sslmode=disable

  - name: grafana
    azs: ((azs))
    instances: 1
    vm_type: medium
    persistent_disk: 1_024
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: grafana
        release: prometheus
        properties:
          grafana:
            database:
              type: postgres
              port: 5432
              name: grafana
              user: grafana
              password: ((postgres_grafana_password))
            session:
              provider: postgres
              provider_port: 5432
              provider_name: grafana
              provider_user: grafana
              provider_password: ((postgres_grafana_password))
            security:
              admin_user: admin
              admin_password: ((grafana_password))
              secret_key: ((grafana_secret_key))
            dashboards:
            prometheus:
              dashboard_folders:
                - name: Grafana
                  files:
                    - /var/vcap/jobs/grafana_dashboards/*.json
                - name: PostgreSQL
                  files:
                    - /var/vcap/jobs/postgres_dashboards/*.json
                - name: Prometheus
                  files:
                    - /var/vcap/jobs/prometheus_dashboards/*.json
      - name: grafana_dashboards
        release: prometheus
      - name: postgres_dashboards
        release: prometheus
      - name: prometheus_dashboards
        release: prometheus

  - name: nginx
    azs: ((azs))
    instances: 1
    vm_type: medium
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: nginx
        release: prometheus
        properties:
          nginx:
            alertmanager:
              auth_users:
                - name: admin
                  password: ((alertmanager_password))
            prometheus:
              auth_users:
                - name: admin
                  password: ((prometheus_password))

variables:
  - name: alertmanager_password
    type: password
  - name: prometheus_password
    type: password
  - name: postgres_grafana_password
    type: password
  - name: grafana_password
    type: password
  - name: grafana_secret_key
    type: password

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: postgres
  version: latest
- name: prometheus
  version: latest
# - name: cron
#   version: 1.1.3
