resources:
- name: next
  type: time
  source:
    interval: 60s

- name: pipeline_repo
  type: git
  source:
    uri: ((pipelines.foundation_automation_git))
    username: ((secrets.concourse.git_username))
    password: ((secrets.concourse.git_password))
    skip_ssl_verification: true

- name: pipeline_image
  type: registry-image
  source:
    repository: ((foundation.docker_registry))/pcf-admins/clitools
    tag: latest
    username: ((secrets.concourse.harbor_username))
    password: ((secrets.concourse.harbor_password))

- name: check-schedule
  type: time
  source:
    start: 8:00 PM
    stop: 10:00 PM
    location: America/New_York
    interval: 24h

- name: apply-schedule
  type: time
  source:
    start: 10:30 PM
    stop: 11:30 PM
    location: America/New_York
    interval: 24h

- name: send-an-email
  type: email
  source:
    smtp:
      host: ((foundation.smtp_host))
      port: "25"
      skip_ssl_validation: true
      anonymous: true
    from: ((pipelines.email-from))
    to: [ ((pipelines.email-to)) ]

resource_types:
- name: email
  type: docker-image
  source:
    repository: ((foundation.docker_registry))/pcf-admins/email-resource
    tag: latest
    username: ((secrets.concourse.harbor_username))
    password: ((secrets.concourse.harbor_password))

jobs:
- name: update-harbor
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "harbor"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-sso
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "sso"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-rabbitmq
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "rabbitmq"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-splunk
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "splunk"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-spring
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "spring"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
# Too much of a pain right now.  apm vs apmpostgres.  Whats up with that
- name: update-metrics
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "metrics"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-pas
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "pas"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-pasw
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "pasw"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-healthwatch
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "healthwatch"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-redis
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "redis"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
- name: update-cloudcache
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "cloudcache"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
# - name: update-mysql
#   plan:
#   - get: check-schedule
#     trigger: true
#   - get: pipeline_repo
#   - get: pipeline_image
#   - task: update
#     image: pipeline_image
#     file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
#     params:
#       PRODUCT: "mysql"
      # OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      # OM_CLIENT_ID: ((secrets.opsman.client_id))
      # OPSMAN_URL: ((foundation.opsman_url))
      # PIVNET_TOKEN: ((pivnet.api_token))
- name: update-azure_sb
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "azure_sb"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))

- name: update-credhub_sb
  plan:
  - get: check-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: update
    image: pipeline_image
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
    params:
      PRODUCT: "credhub_sb"
      OM_CLIENT_SECRET: ((secrets.opsman.client_secret))
      OM_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_URL: ((foundation.opsman_url))
      PIVNET_TOKEN: ((pivnet.api_token))
# - name: get-info
#   plan:
#   - get: pipeline_repo
#   - get: pipeline_image
#   - task: update
#     image: pipeline_image
#     file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/updates.yml
#     params:
#       PRODUCT: "info"

- name: pending-changes
  plan:
  - get: apply-schedule
    trigger: true
  - get: pipeline_repo
  - get: pipeline_image
  - task: pending-changes
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/check-pending.yml
    image: pipeline_image
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((foundation.opsman_url))
      OPSMAN_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_PASSWORD: ((secrets.opsman.client_secret))
      ENV: ((foundation.name))
    on_success:
      put: send-an-email
      params:
        headers: email/pendingheaders.txt
        subject: email/pendingsubject.txt
        body: email/pending.html
  - put: next
- name: apply-changes
  plan:
  - get: next
    trigger: true
    passed:
    - pending-changes
  - get: pipeline_repo
  - get: pipeline_image
  - task: apply-changes
    file: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/apply-updates.yml
    image: pipeline_image
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((foundation.opsman_url))
      OPSMAN_CLIENT_ID: ((secrets.opsman.client_id))
      OPSMAN_PASSWORD: ((secrets.opsman.client_secret))
      ENV: azfog
    on_success:
      put: send-an-email
      params:
        headers: email/headers.txt
        subject: email/subject.txt
        body: email/body.html
    on_failure:
      put: send-an-email
      params:
        headers: email/headers.txt
        subject: email/subject.txt
        body: email/body.html
