resources:
- name: pcf-run-report
  type: git
  source:
    uri: ((pipelines.swiss_army_git))
    username: ((secrets.concourse.git_username))
    password: ((secrets.concourse.git_password))
    branch: master
    skip_ssl_verification: true

- name: schedule
  type: time
  source:
   start: ((env_report_schedule_start))
   stop: ((env_report_schedule_stop))
   location: America/New_York
   interval: ((env_report_interval))

- name: pipeline_image
  type: docker-image
  source:
    repository: ((pipelines.docker_registry))/pcf-admins/clitools
    insecure_registries: [ ((pipelines.docker_registry)) ]

jobs:
- name: gather-data
  plan:
  - get: schedule
    trigger: true
  - get: pcf-run-report
  - get: pipeline_image
  - task: generate-files
    file: pcf-run-report/tasks/env-report/task.yml
    image: pipeline_image
    params:
      BOSH_ADMIN_CLIENT: ((bosh_admin.username))
      PCF_SCRT: ((bosh_admin.password))
      PCF_URL: ((PCF_URL))
      PCF_CERT: ((PCF_CERT))
      PCF_ENV: ((PCF_ENV))
      RPT_GIT: ((RPT_GIT))
      GIT_CERT: ((git_key.private_key))
      PCF_DIRECTOR: ((PCF_DIRECTOR))
      CF_API: ((CF_API))
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_url))
      OPSMAN_CLIENT_ID: ((opsman_admin.username))
      OPSMAN_PASSWORD: ((opsman_admin.password))
