# when deploying to an external BOSH Director, Prometheus can't find firehose_exporter through service discovery
# (because it will only discover VMs managed by OpsManager Director). Therefore we collocate firehose_exporter
# to make it easy to discover (it's on localhost)

# delete firehose instance_group
- type: remove
  path: /instance_groups/name=firehose

# run firehose_exporter job on the prometheus instance_group
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: firehose_exporter
    release: prometheus
    properties:
      firehose_exporter:
        doppler:
          max_retry_count: 300
          subscription_id: "((PCF_ENV))"
        logging:  
          url: wss://doppler.((system_domain)):443
          use_legacy_firehose: true
        metrics:
          environment: "((PCF_ENV))"
        skip_ssl_verify: ((skip_ssl_verify))
        uaa:
          url: https://uaa.((system_domain))
          client_id: firehose_exporter
          client_secret: "((/uaa_clients_firehose_exporter_secret))"

# add local firehose_exporter as a target
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: firehose_exporter
    static_configs:
    - targets:
      - localhost:9186
