resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: ((pipelines.docker_registry))/pcf-admins/pivnet-resource
    insecure_registries: [ ((pipelines.docker_registry)) ]
    tag: latest

- name: email
  type: docker-image
  source:
    repository: ((pipelines.docker_registry))/pcf-admins/email-resource
    tag: ((docker-tag))
    insecure_registries: [ ((pipelines.docker_registry)) ]

resources:
- name: next
  type: time
  source:
    interval: 60s
- name: pcf-apply-pipeline
  type: git
  source:
    uri: ((pipelines.swiss_army_git))
    username: ((secrets.concourse.git_username))
    password: ((secrets.concourse.git_password))
    skip_ssl_verification: true
- name: pipeline_image
  type: docker-image
  source:
    repository: ((pipelines.docker_registry))/czero/cflinuxfs2
    insecure_registries: [ ((pipelines.docker_registry)) ]
  
- name: send-an-email
  type: email
  source:
    smtp:
      host: ((smtp_host))
      port: "25"
      skip_ssl_validation: true
      anonymous: true
    from: ((email-from))
    to: [ ((email-to)) ]


jobs:
- name: pending-changes
  plan:
  - aggregate:
    - get: pcf-apply-pipeline
    - get: pipeline_image
  - task: pending-changes
    file: pcf-apply-pipeline/tasks/pending-changes/task.yml
    image: pipeline_image
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_url))
      OPSMAN_CLIENT_ID: ((opsman_admin.username))
      OPSMAN_PASSWORD: ((opsman_admin.password))
      ENV: ((ENV))
    on_success:
      put: send-an-email
      params:
        headers: email/pendingheaders.txt
        subject: email/pendingsubject.txt
        body: email/pending.html
  - put: next
- name: apply-changes
  plan:
  - aggregate:
    - get: next
      trigger: true
      passed:
      - pending-changes
    - get: pcf-apply-pipeline
    - get: pipeline_image
  - task: apply-changes
    file: pcf-apply-pipeline/tasks/apply-changes/task.yml
    image: pipeline_image
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_url))
      OPSMAN_CLIENT_ID: ((opsman_admin.username))
      OPSMAN_PASSWORD: ((opsman_admin.password))
      ENV: ((ENV))
    on_success:
      put: send-an-email
      params:
        headers: email/headers.txt
        subject: email/subject.txt
        body: email/body.html
    on_failure:
      put: send-an-email
      params:
        headers: email/headers.txt
        subject: email/subject.txt
        body: email/body.html
