{
 "title": "Alert Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Platform Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CF push success/fail",
   "type": "graph",
   "description": "cf push success and failure",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "firehose_value_metric_healthwatch_health_check_cli_command_success",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Bad Gateways",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(firehose_counter_event_gorouter_bad_gateways_total[1h])",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Rabbit Instances",
   "type": "graph",
   "description": "Monitor  Rabbit instances",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_erlang_reachable_nodes{bosh_deployment!~\".*service-instance.*\"}",
     "legendFormat": "{{environment}}-{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Low Disk",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_ephemeral_disk_percent{bosh_deployment!=\"bosh-health-check\",bosh_job_name!~\"^compilation.*\"}) by(bosh_name, bosh_deployment, bosh_job_name, bosh_job_index, bosh_job_ip) > 80",
     "legendFormat": "{{bosh_deployment}} - {{bosh_job_name}} - {{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Unhealthy cells",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "bosh_job_healthy{bosh_deployment!=\"bosh-health-check\"} < 1",
     "legendFormat": "{{bosh_job_name}}-{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Cells < 3GB RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory) by(environment,bosh_job_name,bosh_job_ip) < 3072",
     "legendFormat": "{{environment}}-{{bosh_job_name}}-{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Alert Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Alert Manager Alerts",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "ALERTS{alertname!~\"CFApp.*\",alertstate=~\"firing\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unhealthy Applications",
     "type": "graph",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ALERTS {alertname=~\"CFApp.*\"})",
       "legendFormat": "Apps"
      }
     ]
    },
    {
     "title": "Unhealthy Applications",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(ALERTS {alertname=\"CFAppCrashed\"}) without(alertstate,deployment,service,environment)"
      }
     ]
    }
   ]
  }
 ]
}