{
 "title": "Environment Allocations",
 "tags": [ "public" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running Applications Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cf_application_instances_running)"
    }
   ]
  },
  {
   "title": "Total Allocated RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(cf_application_memory_mb) by(application_id, organization_name) * sum(cf_application_instances_running) by (application_id, organization_name))"
    }
   ]
  },
  {
   "title": "Windows/Linux Allocations",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(firehose_value_metric_rep_container_count) by (bosh_job_name)"
    }
   ]
  },
  {
   "title": "AI Count",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(cf_application_instances) by (organization_name)"
    },
    {
     "expr": "sum(cf_application_instances_running) by (organization_name)"
    },
    {
     "expr": "sum(sum(cf_application_memory_mb) by(application_id, organization_name, quota_name) * sum(cf_application_instances_running) by (application_id, organization_name)) by(organization_name, quota_name)"
    }
   ]
  },
  {
   "title": "HTTP Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Thousands" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_total_requests_total[30m]))"
    }
   ]
  },
  {
   "title": "RAM remaining for allocation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"diego_cell\"}) - sum(firehose_value_metric_rep_capacity_allocated_memory{bosh_job_name=\"diego_cell\"})",
     "legendFormat": "Shared-Linux"
    },
    {
     "expr": "sum(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"}) - sum(firehose_value_metric_rep_capacity_allocated_memory{bosh_job_name=\"windows_diego_cell\"})",
     "legendFormat": "Shared-Windows"
    },
    {
     "expr": "sum(firehose_value_metric_rep_capacity_total_memory{bosh_deployment=~\"p-isolation-segment.*\"}) - sum(firehose_value_metric_rep_capacity_allocated_memory{bosh_deployment=~\"p-isolation-segment.*\"})",
     "legendFormat": "Lab-Linux"
    },
    {
     "expr": "sum(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_lab_wrt\"}) - sum(firehose_value_metric_rep_capacity_allocated_memory{bosh_job_name=\"windows_diego_cell_lab_wrt\"})",
     "legendFormat": "Lab-Windows"
    },
    {
     "expr": "sum(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_frms_lab\"}) - sum(firehose_value_metric_rep_capacity_allocated_memory{bosh_job_name=\"windows_diego_cell_frms_lab\"})",
     "legendFormat": "FRMS-Isolated"
    }
   ]
  },
  {
   "title": "Buildpacks in use",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(cf_application_info{space_name!=\"healthwatch\"}) by (buildpack,stack_id)"
    },
    {
     "expr": "sum(cf_stack_info) by (stack_id,stack_name)"
    }
   ]
  },
  {
   "title": "Applications and Stack",
   "type": "table",
   "description": "List of all applications and the stack they are using",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(cf_application_info{organization_name!=\"system\"}) by (application_name,organization_name,space_name,stack_id)"
    },
    {
     "expr": "sum(cf_stack_info) by (stack_id,stack_name)"
    }
   ]
  }
 ]
}