{
 "title": "PAS SLI/SLO's",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "jcc,jca,lvc,lva,pxc,pxa" },
   {
    "name": "cf_slo",
    "label": "CF Push SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   },
   {
    "name": "app_slo",
    "label": "Canary App SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   }
  ]
 },
 "panels": [
  {
   "title": "$environment SLI's & Remaining Error Budget",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "environment"
  },
  {
   "title": "CF Push Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(firehose_value_metric_healthwatch_health_check_cli_command_success{environment=\"$environment\",origin=\"healthwatch\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "CF Push Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_cli_command_success{environment=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $cf_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Test App Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(firehose_value_metric_healthwatch_health_check_canary_app_available{environment=\"$environment\",origin=\"healthwatch\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Test App Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_canary_app_available{environment=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $app_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "CF Push Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_cli_command_success{environment=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $cf_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Test App Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_canary_app_available{environment=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $app_slo) * ($__range_s / 60)"
    }
   ]
  }
 ]
}