{
 "title": "PKS SLI/SLO's",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pks_slo",
    "label": "PKS SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": "label_values(kube_api_success,cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "PKS API Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(pks_api_success[${__range_s}s])"
    }
   ]
  },
  {
   "title": "PKS API Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(pks_api_success[${__range_s}s]) - $pks_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "PKS API Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(pks_api_success[${__range_s}s]) - $pks_slo) * ($__range_s / 60)"
    }
   ]
  },
  { "title": "$cluster_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "cluster_id" },
  {
   "title": "Kube API Availability (By Cluster)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(kube_api_success{cluster_id=\"$cluster_id\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Kube API Error Budget Remaining (By Cluster)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(kube_api_success{cluster_id=\"$cluster_id\"}[${__range_s}s]) - $pks_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Deployment  Success (By Cluster)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(deploy_api_success{cluster_id=\"$cluster_id\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Deployment  Error Budget Remaining (By Cluster)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(deploy_api_success{cluster_id=\"$cluster_id\"}[${__range_s}s]) - $pks_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Kube API Success Error Budget (By Cluster)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(kube_api_success{cluster_id=\"$cluster_id\"}[${__range_s}s]) - $pks_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Deployment Success Error Budget (By Cluster)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(deploy_api_success{cluster_id=\"$cluster_id\"}[${__range_s}s]) - $pks_slo) * ($__range_s / 60)"
    }
   ]
  }
 ]
}