{
 "title": "Scaling Indicators",
 "tags": [ "admins" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Diego Cells - Total Memory Available %",
   "type": "graph",
   "description": "Percentage of remaining memory capacity for a given cell.\n\nWhen to scale:\nTotal memory available should be greater than 10-20% otherwise scale up",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "percentage available" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"cf.*\"}",
     "legendFormat": "cf"
    },
    {
     "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
     "legendFormat": "p-isolation-segment"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"})",
     "legendFormat": "windows"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_lab_wrt\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_lab_wrt\"})",
     "legendFormat": "windows lab"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_frms_lab\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_frms_lab\"})",
     "legendFormat": "windows frms"
    }
   ]
  },
  {
   "title": "Diego Cells - Total Disk Available %",
   "type": "graph",
   "description": "Percentage of remaining disk capacity for a given cell.\n\nWhen to scale:\nTotal disk available should be greater than 10-20% otherwise scale up",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "percentage available" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"cf.*\"}",
     "legendFormat": "cf"
    },
    {
     "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
     "legendFormat": "p-isolation-segment"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell\"})",
     "legendFormat": "windows"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_lab_wrt\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_lab_wrt\"})",
     "legendFormat": "windows lab"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_frms_lab\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_frms_lab\"})",
     "legendFormat": "windows frms"
    }
   ]
  },
  {
   "title": "Diego Cells - Total Container Capacity Available %",
   "type": "graph",
   "description": "Percentage of remaining container capacity for a given cell (regards to the number of containers a cell can host)\n\nWhen to scale:\nTotal container capacity available should be greater than 10-20% otherwise scale up",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "percentage available" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"cf.*\"}",
     "legendFormat": "cf"
    },
    {
     "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
     "legendFormat": "p-isolation-segment"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell\"})",
     "legendFormat": "windows"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_lab_wrt\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_lab_wrt\"})",
     "legendFormat": "windows lab"
    },
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_frms_lab\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_frms_lab\"})",
     "legendFormat": "windows frms"
    }
   ]
  },
  {
   "title": "Firehose - Total Doppler Ingress",
   "type": "graph",
   "description": "Total number of messages (envelopes) coming into the doppler servers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "(in thousands)" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_ingestor_ingested",
     "legendFormat": "Number of Messages Per Min"
    }
   ]
  },
  {
   "title": "Firehose - Doppler Message Rate ",
   "type": "graph",
   "description": "Represents the average rate of envelopes (messages) per Doppler instance. \n\nWhen to scale:\nAverage load on the Doppler instances should be <16,000 envelopes per second, or 1 million envelopes per minute.  Scale up Doppler when this threshold is reached.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "per minute" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_doppler_messages_average_1_m",
     "legendFormat": "Avg Number of Doppler Messages"
    }
   ]
  },
  {
   "title": "Firehose - Dropped Messages",
   "type": "graph",
   "description": "The loss rate occurring as messages are transported from the Loggregator Agent components through the Doppler components to the Firehose endpoints.\n\nWhen to scale:\nShould be less than 1%. Scale up the number of Traffic Controllers and Doppler instances when threshold is reached.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "percentage dropped" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_m",
     "legendFormat": "Firehose Los Rate Per Min"
    },
    {
     "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_h",
     "legendFormat": "Firehose Loss Rate Per Hour"
    }
   ]
  },
  {
   "title": "Firehose - Slow Consumer Drops Delta",
   "type": "graph",
   "description": "Metrics and logs enter the Firehose for transport and exit out of the platform through a consumer nozzle. If the consuming downstream system fails to keep up with the exiting stream of metrics, the Firehose is forced to close the connection to protect itself from back-pressure. The Firehose increments slow_consumer with each connection that it closes because a consumer could not keep up. This represents the change in number of drops.\n\nWhen to scale:\nScale when the rate of Firehose Slow Consumer Drops is irregular for a given environment.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_delta",
     "legendFormat": "Firehose "
    }
   ]
  },
  {
   "title": "Firehose - Slow Consumer Drops Counter",
   "type": "graph",
   "description": "Metrics and logs enter the Firehose for transport and exit out of the platform through a consumer nozzle. If the consuming downstream system fails to keep up with the exiting stream of metrics, the Firehose is forced to close the connection to protect itself from back-pressure. The Firehose increments slow_consumer with each connection that it closes because a consumer could not keep up. This represents the incrementing counter.\n\nWhen to scale:\nScale when the rate of Firehose Slow Consumer Drops is irregular for a given environment.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_total",
     "legendFormat": "Firehose "
    }
   ]
  },
  {
   "title": "Firehose - Adatper Loss Rate",
   "type": "graph",
   "description": "The loss rate of the Syslog Adapters, that is, the total messages dropped as a percentage of the total traffic coming through the Syslog Adapters. Total messages include only logs for bound applications. \n\nWhen to scale:\nShould be less than 1% otherwise performance test your syslog server, review the logs of the syslog consuming system for intake and other performance issues that indicate a need to scale the consuming system. ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "percentage dropped" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_syslog_drain_adapter_loss_rate_1_m",
     "legendFormat": "Firehose Syslog Loss Rate Per Min"
    }
   ]
  },
  {
   "title": "Reverse Log Proxy - Dropped Messages Counter",
   "type": "graph",
   "description": "Logs and metrics enter Loggregator for transport and then egress through the Reverse Log Proxy (RLP). The RLP drops messages when consumers of the RLP, such as monitoring tool nozzles, ingest the exiting stream of logs and metrics too slowly.\n\nWhen to scale:\nWhen the rate of RLP dropped, direction egress metrics is continuously increasing, scale the number of traffic controllers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firehose_counter_event_loggregator_rlp_dropped_total",
     "legendFormat": "Firehose"
    }
   ]
  },
  {
   "title": "Reverse Log Proxy - Avg Subscriptions",
   "type": "graph",
   "description": "The Reverse Log Proxy (RLP) limits the number of subscriptions. A subscription is a consumer of the RLP so this metric concerns the number of concurrent consumer of an RLP instance. The maximum subscription count is 1000 per RLP.\n\nWhen to scale:\nWhen the number of subscriptions reaches or crosses, scale up the number of traffic controllers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_loggregator_doppler_subscriptions)",
     "legendFormat": "Average Number of Subscriptions"
    }
   ]
  },
  {
   "title": "Reverse Log Proxy Loss Rate",
   "type": "graph",
   "description": "The loss rate of the reverse log proxies (RLP), that is, the total messages dropped as a percentage of the total traffic coming through the reverse log proxy. Total messages include only logs for bound applications. \n\nWhen to scale:\nShould be less than 1%. Scale up the number of traffic controllers when this threshold is reached",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "percentage dropped" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_healthwatch_syslog_drain_rlp_loss_rate_1_m",
     "legendFormat": "Firehose Syslog Loss Rate Per Min"
    }
   ]
  },
  {
   "title": "Routing - VM CPU Utilization",
   "type": "graph",
   "description": "CPU utilization for each Gorouter\n\nWhen to scale:\nCPU usage should be within a maximum range of 60-70% for the best Gorouter performance. \n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent", "label": "cpu (user) usage" }
   ],
   "targets": [
    {
     "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"router\"}",
     "legendFormat": "Router VM"
    }
   ]
  },
  {
   "title": "UAA - VM CPU Utilization",
   "type": "graph",
   "description": "CPU utilization for each UAA vm\n\nWhen to scale:\nCPU usage should be within a maximum range of 80-90% for the best UAA performance. . ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percent", "label": "cpu (user) usage" }
   ],
   "targets": [
    {
     "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"uaa\"}",
     "legendFormat": "UAA VM"
    }
   ]
  },
  {
   "title": "NFS - Persistent Disk Usage %",
   "type": "graph",
   "description": "PAS internal NFS Server persistent disk usage \n\nWhen to scale:\nTotal usage should be below 75%",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percent", "label": "percent used" }
   ],
   "targets": [
    {
     "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"cf.*\",bosh_job_name=\"nfs_server\"}",
     "legendFormat": "Disk Usage"
    }
   ]
  }
 ]
}