{
 "title": "PAS SLI/SLO's",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cf_slo", "label": "CF Push SLO (%)", "query": "0.90, 0.95, 0.99, 0.995, 0.999" },
   { "name": "app_slo", "label": "Canary App SLO (%)", "query": "0.90, 0.95, 0.99, 0.995, 0.999" }
  ]
 },
 "panels": [
  {
   "title": "Fog SLI's & Remaining Error Budget",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "environment"
  },
  {
   "title": "CF Push Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(firehose_value_metric_healthwatch_health_check_cli_command_success{environment=\"fog\",origin=\"healthwatch\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "CF Push Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_cli_command_success{environment=\"fog\",origin=\"healthwatch\"}[${__range_s}s]) - $cf_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Test App Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(firehose_value_metric_healthwatch_health_check_canary_app_available{environment=\"fog\",origin=\"healthwatch\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Test App Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_canary_app_available{environment=\"fog\",origin=\"healthwatch\"}[${__range_s}s]) - $app_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "CF Push Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_cli_command_success{environment=\"fog\",origin=\"healthwatch\"}[${__range_s}s]) - $cf_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Test App Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(firehose_value_metric_healthwatch_health_check_canary_app_available{environment=\"fog\",origin=\"healthwatch\"}[${__range_s}s]) - $app_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "CF push success/fail",
   "type": "graph",
   "description": "cf push success and failure",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "0=Fail 1=Success" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "firehose_value_metric_healthwatch_health_check_cli_command_success",
     "legendFormat": "success/fail",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}