{
 "title": "Service SLI/SLO's",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ecs_slo",
    "label": "ECS SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   },
   {
    "name": "rabbit_ondmd_slo",
    "label": "Rabbit Ondmd SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   },
   {
    "name": "rabbit_shared_slo",
    "label": "Rabbit Shared SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   },
   {
    "name": "credhub_slo",
    "label": "Credhub SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   },
   {
    "name": "scs3_slo",
    "label": "Spring SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   },
   {
    "name": "p_redis_slo",
    "label": "p-redis SLO (%)",
    "query": "0.90, 0.95, 0.99, 0.995, 0.999,0.9999"
   }
  ]
 },
 "panels": [
  {
   "title": "ECS Broker Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(ecs_metric_success[${__range_s}s])"
    }
   ]
  },
  {
   "title": "ECS Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(ecs_metric_success[${__range_s}s]) - $ecs_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Rabbit On-Demand Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(rabbitmq_ondmd_svc_creation_availability[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Rabbit On-Demand Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(rabbitmq_ondmd_svc_creation_availability[${__range_s}s]) - $rabbit_ondmd_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Rabbit Shared Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(rabbitmq_shared_svc_creation_availability[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Rabbit Shared Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(rabbitmq_shared_svc_creation_availability[${__range_s}s]) - $rabbit_shared_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "ECS Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(ecs_metric_success[${__range_s}s]) - $ecs_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Rabbit On-Demand Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(rabbitmq_ondmd_svc_creation_availability[${__range_s}s]) - $rabbit_ondmd_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Rabbit Shared Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(rabbitmq_shared_svc_creation_availability[${__range_s}s]) - $rabbit_shared_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Credhub Broker Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(credhub_svc_creation_availability[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Credhub Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(credhub_svc_creation_availability[${__range_s}s]) - $credhub_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Spring Cloud Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(scs3_creation_availability[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Spring Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(scs3_creation_availability[${__range_s}s]) - $scs3_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "p-redis Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(redis_creation_availability[${__range_s}s])"
    }
   ]
  },
  {
   "title": "p-redis Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 7 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(redis_creation_availability[${__range_s}s]) - $p_redis_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Credhub Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(credhub_svc_creation_availability[${__range_s}s]) - $credhub_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Spring Cloud Services Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(scs3_creation_availability[${__range_s}s]) - $scs3_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "p-redis Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(redis_creation_availability[${__range_s}s]) - $p_redis_slo) * ($__range_s / 60)"
    }
   ]
  }
 ]
}