resources:
- name: pcf-health-check
  type: git
  source:
    uri: ((pipelines.swiss_army_git))
    username: ((secrets.concourse.git_username))
    password: ((secrets.concourse.git_password))
    skip_ssl_verification: true

- name: schedule
  type: time
  source:
    start: ((pipelines.health-check-schedule-start))
    stop: ((pipelines.health-check-schedule-stop))
    location: America/New_York
    interval: ((pipelines.health-check-interval))
- name: send-an-email
  type: email
  source:
    smtp:
      host: ((pipelines.smtp_host))
      port: "25"
      skip_ssl_validation: true
      anonymous: true
    from: ((pipelines.email-from))
    to: [ ((pipelines.email-to)) ]

- name: pipeline_image
  type: docker-image
  source:
    insecure_registries:
    - ((pipelines.docker_registry))
    repository: ((pipelines.docker_registry))/pcf-admins/clitools
    # username: ((secrets.concourse.harbor_username))
    # password: ((secrets.concourse.harbor_password))

resource_types:
- name: email
  type: docker-image
  source:
    insecure_registries:
    - ((pipelines.docker_registry))
    repository: ((pipelines.docker_registry))/pcf-admins/email-resource
    tag: latest
    # username: ((secrets.concourse.harbor_username))
    # password: ((secrets.concourse.harbor_password))

jobs:
- name: scheduled-smoketests
  plan:
  - get: schedule
    trigger: false
  - get: pcf-health-check
  - get: pipeline_image
  - task: run-smoke-tests
    image: pipeline_image
    file: pcf-health-check/tasks/health-check/task.yml
    params:
      BOSH_ADMIN_CLIENT: ((secrets.concourse.bosh_admin_username))
      PCF_SCRT: ((secrets.concourse.bosh_admin_password))
      PCF_URL: ((pipelines.PCF_DIRECTOR))
      PCF_CERT: ((certs.PCF_CERT))
      VERBOSE_TEST: ((VERBOSE_TEST))
      PCF_ENV: ((foundation.name))
  on_failure:
    put: send-an-email
    params:
      headers: email/smoketestheaders.txt
      subject: email/smoketestsubject.txt
      body: email/smoketest.html